version: '3.2'
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
          - /mnt/new/changedection-data:/datastore
      ports:
        - 5000:5000
      restart: unless-stopped
      depends_on:
          playwright-chrome:
            condition: service_started

    playwright-chrome:
      hostname: playwright-chrome
      image: dgtlmoon/sockpuppetbrowser:latest
      cap_add:
        - SYS_ADMIN
      restart: unless-stopped
      environment:
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1024
        - SCREEN_DEPTH=16
        - MAX_CONCURRENT_CHROME_PROCESSES=10

volumes:
  changedetection-data:

